# Generated by Django 5.0.6 on 2024-06-17 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opciones', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CasinoColacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_servicio', models.DateField()),
                ('id_estado', models.IntegerField(choices=[(0, 'No visible'), (1, 'visible')], default=1)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('id_opciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.opciones')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('activo', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_servicio', models.DateField()),
                ('cantidad_almuerzo', models.IntegerField(default=1)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('impreso', models.IntegerField(choices=[(0, 'No Impreso'), (1, 'Impreso')], default=0)),
                ('casino_colacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.casinocolacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.usuarios')),
            ],
        ),
    ]
