# Generated by Django 5.0.6 on 2024-06-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_alter_casinocolacion_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casinocolacion',
            name='visible',
            field=models.IntegerField(choices=[(1, 'Si'), (2, 'No')], default=1),
        ),
    ]
