# Generated by Django 5.0.6 on 2024-06-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0004_alter_casinocolacion_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casinocolacion',
            name='visible',
        ),
    ]
