# Generated by Django 5.0.6 on 2024-06-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0006_tipousuario_usuarios_programacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='activo',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
    ]
