# Generated by Django 5.0.6 on 2024-06-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0007_alter_usuarios_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casinocolacion',
            old_name='fecha_creacion',
            new_name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='casinocolacion',
            name='fecha_aprobacion',
        ),
        migrations.AlterField(
            model_name='casinocolacion',
            name='id_estado',
            field=models.IntegerField(choices=[(0, 'No visible'), (1, 'visible')], default=1),
        ),
    ]
