# Generated by Django 5.0.6 on 2024-06-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0008_rename_fecha_creacion_casinocolacion_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='impreso',
            field=models.IntegerField(choices=[(0, 'No Impreso'), (1, 'Impreso')], default=0),
        ),
    ]
