# Generated by Django 5.0.6 on 2024-06-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0009_programacion_impreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacion',
            name='casino_colacion',
        ),
        migrations.AddField(
            model_name='programacion',
            name='menu_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='programacion',
            name='nom_menu',
            field=models.CharField(default='Nombre por defecto', max_length=255),
        ),
    ]
