# Generated by Django 5.0.6 on 2024-06-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0010_remove_programacion_casino_colacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacion',
            name='fecha_ingreso',
        ),
        migrations.AlterField(
            model_name='programacion',
            name='cantidad_almuerzo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='impreso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='menu_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='nom_menu',
            field=models.CharField(max_length=255),
        ),
    ]
