# Generated by Django 5.0.6 on 2024-06-21 02:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0011_remove_programacion_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='fecha_impreso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programacion',
            name='fecha_seleccion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
